# Generated by Django 3.1.7 on 2021-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tip', models.TextField(max_length=245)),
                ('timeStamps', models.DateTimeField()),
                ('author', models.CharField(max_length=10)),
                ('mediaUrl', models.URLField(blank=True, max_length=2545, null=True)),
                ('totalLike', models.IntegerField()),
                ('totalRetweet', models.IntegerField()),
            ],
        ),
    ]
