# Generated by Django 3.1.7 on 2021-03-16 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=245, primary_key=True, serialize=False)),
                ('tip', models.TextField(max_length=245)),
                ('timeStamps', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=10)),
                ('mediaUrl', models.URLField(blank=True, max_length=2545, null=True)),
                ('totalLike', models.IntegerField()),
                ('totalRetweet', models.IntegerField()),
            ],
            options={
                'ordering': ['-totalLike'],
            },
        ),
    ]
