# Generated by Django 3.1.7 on 2021-03-12 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210312_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timeStamps',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 11, 23, 44, 863303, tzinfo=utc)),
        ),
    ]
