# Generated by Django 3.1.7 on 2021-03-12 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20210312_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timeStamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
