# Generated by Django 3.1.7 on 2021-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20210312_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
